services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
    env_file:
      - docker/prod.env
    depends_on:
      - api
      - ws

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    expose:
      - 8000
    env_file:
      - docker/prod.env
    command: [ "gunicorn", "--bind", "0.0.0.0:8000", "backend.wsgi:application" ]
    depends_on:
      - postgres
      - rabbitmq
      - celery

  ws:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    expose:
      - 8001
    env_file:
      - docker/prod.env
    command: [ "daphne", "-b", "0.0.0.0", "-p", "8001", "backend.asgi:application" ]
    depends_on:
      - postgres
      - rabbitmq
      - redis

  celery:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    env_file:
      - docker/prod.env
    command: sh -c "python manage.py migrate && celery -A backend worker -l INFO"
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:16
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - docker/prod.env

  rabbitmq:
    image: rabbitmq:3.13-management
    expose:
      - 5672
      - 15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - docker/prod.env

  redis:
    image: redis:7
    expose:
      - 6379
    volumes:
      - redis_data:/data
    env_file:
      - docker/prod.env

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:
