services:
  nginx:
    image: nginx:1.27
    ports:
      - 80:80
    env_file:
      - docker/.env
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - docker/.env
    volumes:
      - .:/app
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    depends_on:
      - postgres
      - rabbitmq

  celery:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    env_file:
      - docker/.env
    volumes:
      - .:/app
    command: sh -c "python manage.py migrate && celery -A backend worker -l INFO"
    depends_on:
      - postgres
      - rabbitmq

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - 5173:5173
    env_file:
      - docker/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]
    depends_on:
      - nginx

  postgres:
    image: postgres:16
    ports:
      - 54320:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - docker/.env

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - docker/.env

volumes:
  postgres_data:
  rabbitmq_data: