env: prod

services:
  api:
    replicas: 2
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "1"
  queue:
    requests:
      memory: "128Mi"
      cpu: "75m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  worker:
    replicas: 2
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "1"

image:
  name: registry.digitalocean.com/registry-first/template_api
  version: latest

imagePullPolicy: IfNotPresent