apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  namespace: {{ .Release.Namespace }}
data:
  {{- if eq .Values.env "dev" }}
  PYTHONUNBUFFERED: "1"

  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "*"

  POSTGRES_DB: "defaultdb"
  POSTGRES_USER: "doadmin"
  POSTGRES_HOST: "private-db-first-do-user-18564023-0.m.db.ondigitalocean.com"
  POSTGRES_PORT: "25060"

  CELERY_BROKER_URL: "pyamqp://guest@queue-service//"
  {{- end }}

  {{- if eq .Values.env "prod" }}
  PYTHONUNBUFFERED: "1"

  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "*"

  POSTGRES_DB: "defaultdb"
  POSTGRES_USER: "doadmin"
  POSTGRES_HOST: "private-db-first-do-user-18564023-0.m.db.ondigitalocean.com"
  POSTGRES_PORT: "25060"

  CELERY_BROKER_URL: "pyamqp://guest@queue-service//"
  {{- end }}
