name: Deploy to Production

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install helm
      uses: azure/setup-helm@v4.2.0

    - name: Determine deployment environment
      run: |
        deploy_env=$( [ "${{ github.ref_name }}" = "dev" ] && echo "dev" || echo "prod" ) 
        echo "DEPLOY_ENV=$deploy_env" >> $GITHUB_ENV

    - name: Test deployment environment to be correct
      run: echo $DEPLOY_ENV

    - name: Inject ConfigMap as env vars into runner
      run: |
        helm template main ./k8s \
          --values ./k8s/values-$DEPLOY_ENV.yaml \
          --namespace $DEPLOY_ENV \
          --show-only templates/configmap.json \
          > ./k8s/_configmap_output.json
        env_vars=$(python ./k8s/configmap_to_env_vars.py)
        echo "$env_vars" >> $GITHUB_ENV

    - name: Inject secrets into runner
      run: |
        echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> $GITHUB_ENV
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_ENV


    - name: Run tests
      run: |
        python manage.py test

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME=registry.digitalocean.com/${{ vars.CONTAINER_REGISTRY }}/${{ vars.IMAGE_NAME }}
        IMAGE_VERSION=$DEPLOY_ENV-${{ github.run_number }}
        docker build -t $IMAGE_NAME:$IMAGE_VERSION .
        docker push $IMAGE_NAME:$IMAGE_VERSION

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: "v1.32.0"

    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ vars.CLUSTER_NAME }}

    - name: Upgrade Helm Chart
      run: |
        helm upgrade --install main ./k8s \
          --namespace $DEPLOY_ENV \
          --set image.version=$IMAGE_VERSION \
          --wait
