name: Deploy to prod

on:
  push:
    branches:
      - trigger-workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=registry.digitalocean.com/${{ vars.CONTAINER_REGISTRY }}/${{ vars.IMAGE_NAME }}
          IMAGE_VERSION=$(git rev-list --count HEAD)
          IMAGE_FULL_NAME="${IMAGE_NAME}:${IMAGE_VERSION}" 
  
          echo "IMAGE_VERSION=$IMAGE_VERSION" >> $GITHUB_ENV
          echo "IMAGE_FULL_NAME=$IMAGE_FULL_NAME" >> $GITHUB_ENV
  
          docker build -t "$IMAGE_FULL_NAME" -f ./docker/api/Dockerfile .

      - name: Run tests
        run: |
          docker run \
          -e PYTHONBUFFERED=1 \
          -e DJANGO_SECRET_KEY=insecure_key_for_testing_only \
          -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
          $IMAGE_FULL_NAME \
          python manage.py test

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Push image
        run: |
          doctl registry login --expiry-seconds 600
          docker push $IMAGE_FULL_NAME
          
      - name: Install python (for workflow scripting)
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"

      - name: Update image
        run: |
          doctl app spec get ${{ secrets.DIGITALOCEAN_APP_ID }} --format json >> ./.github/_app_spec.json
          python ./.github/update_app_spec.py
          doctl app update --spec ./.github/_app_spec.json ${{ secrets.DIGITALOCEAN_APP_ID }}