name: Deploy to Production

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Determine env
      run: |
        ENV=$( [ "${{ github.head_ref || github.ref_name }}" = "dev" ] && echo "dev" || echo "prod" )

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python manage.py test

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME=registry.digitalocean.com/${{ vars.CONTAINER_REGISTRY }}/${{ vars.IMAGE_NAME }}
        IMAGE_VERSION=$ENV-${{ github.run_number }}
        docker build -t $IMAGE_NAME:$IMAGE_VERSION .
        docker push $IMAGE_NAME:$IMAGE_VERSION

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: "v1.32.0"

    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ vars.CLUSTER_NAME }}

    - name: Upgrade Helm Chart
      run: |
        helm upgrade --install main ./k8s \
          --namespace $ENV \
          --set image.version=$IMAGE_VERSION \
          --wait
